### PR TITLE
fixed zbx_docker_perm() to get container naming functional on CentOSs…

### PR DESCRIPTION
**Pull request by juwi**
… dockerroot group

In reference to Issue #17 here's a quick fix for CentOS with dockerroot group

### CODE REVIEW

**Comment by jangaraj** [comment]
You pull request will fix zbx_docker_perm problem, but then code has problem to use docker socket, because permissions (only user root and group root is allowed to use socket):
```
[root@docker_extra_centos_16]# id zabbix
uid=996(zabbix) gid=994(zabbix) groups=994(zabbix),995(dockerroot)
[root@docker_extra_centos_16]# ls -lah /var/run/docker.sock
srw-rw----. 1 root root 0 Jul 30 18:08 /var/run/docker.sock
```

For reference docker-io 1.5:
```
[root@docker-io_15]# id zabbix
uid=498(zabbix) gid=499(zabbix) groups=499(zabbix),495(docker)
[root@docker-io_15]#  ls -lah /var/run/docker.sock
srw-rw---- 1 root docker 0 Mar 14 16:42 /var/run/docker.sock
```
Group docker is allowed to use docker socket. 

Workaround: edit zabbix_agentd.conf and allow root
```
AllowRoot=1
```
Zabbix agent will have root permissions and it'll be able to execute docker socket query. You should to see in you log file:
```
9997:20150730:184252.887 Docker's socket query: GET /_ping HTTP/1.0
9997:20150730:184252.888 Docker's socket response: OK
9997:20150730:184252.888 Docker's socket works - extended docker metrics are available
```

I'll try to reach maintainer of docker Centos 7 extra package.

**Comment by lsm5** [comment]
Hi, we've been creating the dockerroot group, but haven't really been using it yet. Giving docker or similar groups access to docker.sock would allow bypassing sudo and can be a risk, so we're not enabling that in the default install.

Alternatively, if you don't care about Red Hat patches and are cool with using vanilla upstream docker, upstream docker now maintains rpm builds for CentOS which probably makes docker.sock accessible to docker group. Their docs have info on how to get those.

Does that help?

**Comment by jangaraj** [comment]
Thank you @lsm5 . I'll update my doc - full root permissions will be required for RHEL/Centos Docker monitoring.

**Comment by juwi** [comment]
No problem ;-)

Just a quick explanation about how I got this working, though as there seems to be confusion.
I fixed the docker.sock permissions to root:dockerroot, as my initial thought was, that the root:root permissions must be a bug and assumed that this would be addressed with the next update to the package (thanks to @lsm5 for making clear that this isn't the case). Changing the socket permissions to me still seems cleaner (and less risky) than giving zabbix root permissions, though. Of course I could also just create a docker group and change the socket permissions to that. Wouldn't make the hack any uglier than it already is, I guess.

@lsm5 I do understand the risk, however with the group seemingly being unused, what is the idea behind it, then?

**Comment by rhatdan** [comment]
We are working on getting patches into docker for Authentication and later Authorization and logging.

Currently the ability to talk to the docker socket allow full root access.

```
$ docker run -ti -v /:/host --privileged fedora chroot /host
``

You own the system, and there is no log record of you doing this.

We recommend using sudo for access to the docker daemon, until we get proper logging, and authorization.

**Comment by jangaraj** [comment]
@rhatdan (un)fortunately this is shared library module -> I can't use sudo concept + it's not dockerized (for now). It'll be fun (from this module point of view) when RHEL implements authentication and authorization :-) 

Where can I follow your docker progress (repo, mailing list,...)?

**Comment by rhatdan** [comment]
Logging: https://github.com/docker/docker/pull/14446
Authorization: https://github.com/docker/docker/issues/13697

**Comment by rhatdan** [comment]
We have not submitted anything on Authorization yet, we are still working on our proposal.

Here is what we are currently thinking.

https://github.com/rhatdan/docker-rbac

**Pull request closed without merging**
